name: Admin Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Fix Gradle
        run: |
          rm -rf android
          flutter create . --project-name tune_earn_v27_admin --platforms=android
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: admin-apk
          path: build/app/outputs/flutter-apk/app-release.apk
